export const CALLBACK_ACTIONS = {
  QUESTION_1_OPTION_1: "1.1",
  QUESTION_1_OPTION_2: "1.2",
  QUESTION_2_OPTION_1: "2.1",
  QUESTION_2_OPTION_2: "2.2",
  QUESTION_2_OPTION_3: "2.3",

  STEP_8_BUTTON_REJECT: "STEP_8_BUTTON_REJECT",
  STEP_8_BUTTON_ACCEPT: "STEP_8_BUTTON_ACCEPT",

  STEP_9_BUTTON_REJECT: "STEP_9_BUTTON_REJECT",
  STEP_9_BUTTON_REQUEST_ACCESS: "STEP_9_BUTTON_REQUEST_ACCESS",

  STEP_10_BUTTON_REJECT: "STEP_10_BUTTON_REJECT",
  STEP_10_BUTTON_START: "STEP_10_BUTTON_START",

  STEP_11_BUTTON_REJECT: "STEP_11_BUTTON_REJECT",
  STEP_11_BUTTON_START: "STEP_11_BUTTON_START",

  STEP_11_QUESTION_QUIZ_ANSWER_1: "STEP_11_QUESTION_QUIZ_ANSWER_1",
  STEP_11_QUESTION_QUIZ_ANSWER_2: "STEP_11_QUESTION_QUIZ_ANSWER_2",
  STEP_11_QUESTION_QUIZ_ANSWER_3: "STEP_11_QUESTION_QUIZ_ANSWER_3",
};
